//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Kuznetsov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_DKuznetsovEntities : DbContext
    {

        private static BD_DKuznetsovEntities _context;

        public static BD_DKuznetsovEntities GetContext()
        {
            if (_context == null)
                _context =  new BD_DKuznetsovEntities();
            return _context;
        }

        public BD_DKuznetsovEntities()
            : base("name=BD_DKuznetsovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Strahovoi_agent> Strahovoi_agent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vidi_strahovki> Vidi_strahovki { get; set; }
        public virtual DbSet<Zayavki> Zayavki { get; set; }
    }
}
