//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Kuznetsov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavki
    {
        public int Id_Zayavki { get; set; }
        public string FIO { get; set; }
        public string Telefon { get; set; }
        public string DR { get; set; }
        public string Adres { get; set; }
        public int Id_Strahovki { get; set; }
        public int Id_agent { get; set; }
    
        public virtual Strahovoi_agent Strahovoi_agent { get; set; }
        public virtual Vidi_strahovki Vidi_strahovki { get; set; }
    }
}
